// Matches backend field_order.py exactly
// Each field has: key, label, type, min, max, step, placeholder, options (for select)

export const diseaseConfig = {
  Diabetes: {
    label: "Diabetes",
    description:
      "Predict diabetes risk using glucose, BMI, insulin and clinical markers.",
    color: "blue",
    accent: "bg-blue-600",
    light: "bg-blue-50",
    border: "border-blue-200",
    text: "text-blue-600",
    fields: [
      {
        key: "Pregnancies",
        label: "Pregnancies",
        type: "number",
        min: 0,
        max: 20,
        step: 1,
        placeholder: "0–20",
      },
      {
        key: "Glucose",
        label: "Glucose (mg/dL)",
        type: "number",
        min: 0,
        max: 300,
        step: 1,
        placeholder: "70–200",
      },
      {
        key: "BloodPressure",
        label: "Blood Pressure (mmHg)",
        type: "number",
        min: 0,
        max: 200,
        step: 1,
        placeholder: "60–140",
      },
      {
        key: "SkinThickness",
        label: "Skin Thickness (mm)",
        type: "number",
        min: 0,
        max: 100,
        step: 1,
        placeholder: "0–99",
      },
      {
        key: "Insulin",
        label: "Insulin (μU/mL)",
        type: "number",
        min: 0,
        max: 900,
        step: 1,
        placeholder: "0–846",
      },
      {
        key: "BMI",
        label: "BMI",
        type: "number",
        min: 0,
        max: 70,
        step: 0.1,
        placeholder: "18.5–50",
      },
      {
        key: "DiabetesPedigreeFunction",
        label: "Diabetes Pedigree Function",
        type: "number",
        min: 0,
        max: 3,
        step: 0.001,
        placeholder: "0.078–2.42",
      },
      {
        key: "Age",
        label: "Age (years)",
        type: "number",
        min: 1,
        max: 120,
        step: 1,
        placeholder: "21–81",
      },
    ],
  },

  Heart: {
    label: "Heart Disease",
    description:
      "Assess cardiovascular risk from ECG, cholesterol and chest pain type.",
    color: "red",
    accent: "bg-red-500",
    light: "bg-red-50",
    border: "border-red-200",
    text: "text-red-500",
    fields: [
      {
        key: "age",
        label: "Age (years)",
        type: "number",
        min: 1,
        max: 120,
        step: 1,
        placeholder: "29–77",
      },
      {
        key: "sex",
        label: "Sex",
        type: "select",
        options: [
          { value: 1, label: "Male" },
          { value: 0, label: "Female" },
        ],
      },
      {
        key: "cp",
        label: "Chest Pain Type",
        type: "select",
        options: [
          { value: 0, label: "Typical Angina" },
          { value: 1, label: "Atypical Angina" },
          { value: 2, label: "Non-anginal Pain" },
          { value: 3, label: "Asymptomatic" },
        ],
      },
      {
        key: "trestbps",
        label: "Resting Blood Pressure (mmHg)",
        type: "number",
        min: 80,
        max: 250,
        step: 1,
        placeholder: "94–200",
      },
      {
        key: "chol",
        label: "Cholesterol (mg/dL)",
        type: "number",
        min: 100,
        max: 600,
        step: 1,
        placeholder: "126–564",
      },
      {
        key: "fbs",
        label: "Fasting Blood Sugar > 120 mg/dL",
        type: "select",
        options: [
          { value: 1, label: "Yes" },
          { value: 0, label: "No" },
        ],
      },
      {
        key: "restecg",
        label: "Resting ECG Results",
        type: "select",
        options: [
          { value: 0, label: "Normal" },
          { value: 1, label: "ST-T Wave Abnormality" },
          { value: 2, label: "Left Ventricular Hypertrophy" },
        ],
      },
      {
        key: "thalach",
        label: "Max Heart Rate Achieved",
        type: "number",
        min: 60,
        max: 250,
        step: 1,
        placeholder: "71–202",
      },
      {
        key: "exang",
        label: "Exercise Induced Angina",
        type: "select",
        options: [
          { value: 1, label: "Yes" },
          { value: 0, label: "No" },
        ],
      },
      {
        key: "oldpeak",
        label: "ST Depression (oldpeak)",
        type: "number",
        min: 0,
        max: 10,
        step: 0.1,
        placeholder: "0–6.2",
      },
      {
        key: "slope",
        label: "Slope of Peak Exercise ST",
        type: "select",
        options: [
          { value: 0, label: "Upsloping" },
          { value: 1, label: "Flat" },
          { value: 2, label: "Downsloping" },
        ],
      },
      {
        key: "ca",
        label: "Major Vessels Colored (0–3)",
        type: "select",
        options: [
          { value: 0, label: "0" },
          { value: 1, label: "1" },
          { value: 2, label: "2" },
          { value: 3, label: "3" },
        ],
      },
      {
        key: "thal",
        label: "Thalassemia",
        type: "select",
        options: [
          { value: 1, label: "Normal" },
          { value: 2, label: "Fixed Defect" },
          { value: 3, label: "Reversible Defect" },
        ],
      },
    ],
  },

  Kidney: {
    label: "Kidney Disease",
    description:
      "Detect chronic kidney disease from 24 lab and clinical feature inputs.",
    color: "purple",
    accent: "bg-purple-600",
    light: "bg-purple-50",
    border: "border-purple-200",
    text: "text-purple-600",
    fields: [
      {
        key: "age",
        label: "Age (years)",
        type: "number",
        min: 1,
        max: 120,
        step: 1,
        placeholder: "2–90",
      },
      {
        key: "bp",
        label: "Blood Pressure (mmHg)",
        type: "number",
        min: 50,
        max: 200,
        step: 1,
        placeholder: "50–180",
      },
      {
        key: "sg",
        label: "Specific Gravity",
        type: "select",
        options: [
          { value: 1.005, label: "1.005" },
          { value: 1.01, label: "1.010" },
          { value: 1.015, label: "1.015" },
          { value: 1.02, label: "1.020" },
          { value: 1.025, label: "1.025" },
        ],
      },
      {
        key: "al",
        label: "Albumin (0–5)",
        type: "select",
        options: [0, 1, 2, 3, 4, 5].map((v) => ({
          value: v,
          label: String(v),
        })),
      },
      {
        key: "su",
        label: "Sugar (0–5)",
        type: "select",
        options: [0, 1, 2, 3, 4, 5].map((v) => ({
          value: v,
          label: String(v),
        })),
      },
      {
        key: "rbc",
        label: "Red Blood Cells",
        type: "select",
        options: [
          { value: 0, label: "Normal" },
          { value: 1, label: "Abnormal" },
        ],
      },
      {
        key: "pc",
        label: "Pus Cells",
        type: "select",
        options: [
          { value: 0, label: "Normal" },
          { value: 1, label: "Abnormal" },
        ],
      },
      {
        key: "pcc",
        label: "Pus Cell Clumps",
        type: "select",
        options: [
          { value: 0, label: "Not Present" },
          { value: 1, label: "Present" },
        ],
      },
      {
        key: "ba",
        label: "Bacteria",
        type: "select",
        options: [
          { value: 0, label: "Not Present" },
          { value: 1, label: "Present" },
        ],
      },
      {
        key: "bgr",
        label: "Blood Glucose Random (mg/dL)",
        type: "number",
        min: 70,
        max: 500,
        step: 1,
        placeholder: "70–490",
      },
      {
        key: "bu",
        label: "Blood Urea (mg/dL)",
        type: "number",
        min: 1,
        max: 400,
        step: 1,
        placeholder: "1.5–391",
      },
      {
        key: "sc",
        label: "Serum Creatinine (mg/dL)",
        type: "number",
        min: 0.4,
        max: 80,
        step: 0.1,
        placeholder: "0.4–76",
      },
      {
        key: "sod",
        label: "Sodium (mEq/L)",
        type: "number",
        min: 100,
        max: 170,
        step: 1,
        placeholder: "111–163",
      },
      {
        key: "pot",
        label: "Potassium (mEq/L)",
        type: "number",
        min: 2,
        max: 50,
        step: 0.1,
        placeholder: "2.5–47",
      },
      {
        key: "hemo",
        label: "Hemoglobin (g/dL)",
        type: "number",
        min: 3,
        max: 20,
        step: 0.1,
        placeholder: "3.1–17.8",
      },
      {
        key: "pcv",
        label: "Packed Cell Volume (%)",
        type: "number",
        min: 9,
        max: 60,
        step: 1,
        placeholder: "9–54",
      },
      {
        key: "wc",
        label: "White Blood Cell Count (cells/μL)",
        type: "number",
        min: 2000,
        max: 30000,
        step: 100,
        placeholder: "2200–26400",
      },
      {
        key: "rc",
        label: "Red Blood Cell Count (millions/μL)",
        type: "number",
        min: 2,
        max: 8,
        step: 0.1,
        placeholder: "2.1–8",
      },
      {
        key: "htn",
        label: "Hypertension",
        type: "select",
        options: [
          { value: 1, label: "Yes" },
          { value: 0, label: "No" },
        ],
      },
      {
        key: "dm",
        label: "Diabetes Mellitus",
        type: "select",
        options: [
          { value: 1, label: "Yes" },
          { value: 0, label: "No" },
        ],
      },
      {
        key: "cad",
        label: "Coronary Artery Disease",
        type: "select",
        options: [
          { value: 1, label: "Yes" },
          { value: 0, label: "No" },
        ],
      },
      {
        key: "appet",
        label: "Appetite",
        type: "select",
        options: [
          { value: 1, label: "Good" },
          { value: 0, label: "Poor" },
        ],
      },
      {
        key: "pe",
        label: "Pedal Edema",
        type: "select",
        options: [
          { value: 1, label: "Yes" },
          { value: 0, label: "No" },
        ],
      },
      {
        key: "ane",
        label: "Anemia",
        type: "select",
        options: [
          { value: 1, label: "Yes" },
          { value: 0, label: "No" },
        ],
      },
    ],
  },

  Liver: {
    label: "Liver Disease",
    description:
      "Identify liver disease risk through bilirubin, enzyme levels and protein ratios.",
    color: "amber",
    accent: "bg-amber-500",
    light: "bg-amber-50",
    border: "border-amber-200",
    text: "text-amber-600",
    fields: [
      {
        key: "Age",
        label: "Age (years)",
        type: "number",
        min: 1,
        max: 120,
        step: 1,
        placeholder: "4–90",
      },
      {
        key: "Gender",
        label: "Gender",
        type: "select",
        options: [
          { value: 1, label: "Male" },
          { value: 0, label: "Female" },
        ],
      },
      {
        key: "Total_Bilirubin",
        label: "Total Bilirubin (mg/dL)",
        type: "number",
        min: 0.1,
        max: 80,
        step: 0.1,
        placeholder: "0.4–75",
      },
      {
        key: "Direct_Bilirubin",
        label: "Direct Bilirubin (mg/dL)",
        type: "number",
        min: 0.1,
        max: 20,
        step: 0.1,
        placeholder: "0.1–19.7",
      },
      {
        key: "Alkaline_Phosphotase",
        label: "Alkaline Phosphotase (IU/L)",
        type: "number",
        min: 60,
        max: 3000,
        step: 1,
        placeholder: "63–2110",
      },
      {
        key: "Alamine_Aminotransferase",
        label: "Alamine Aminotransferase (IU/L)",
        type: "number",
        min: 7,
        max: 2000,
        step: 1,
        placeholder: "10–2000",
      },
      {
        key: "Aspartate_Aminotransferase",
        label: "Aspartate Aminotransferase (IU/L)",
        type: "number",
        min: 10,
        max: 5000,
        step: 1,
        placeholder: "10–4929",
      },
      {
        key: "Total_Protiens",
        label: "Total Proteins (g/dL)",
        type: "number",
        min: 2,
        max: 10,
        step: 0.1,
        placeholder: "2.7–9.6",
      },
      {
        key: "Albumin",
        label: "Albumin (g/dL)",
        type: "number",
        min: 0.5,
        max: 6,
        step: 0.1,
        placeholder: "0.9–5.5",
      },
      {
        key: "Albumin_and_Globulin_Ratio",
        label: "Albumin & Globulin Ratio",
        type: "number",
        min: 0.1,
        max: 3,
        step: 0.01,
        placeholder: "0.3–2.8",
      },
    ],
  },
};

export const DISEASES = Object.keys(diseaseConfig);
